services:
  site:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - simple_net

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./src/static:/var/www/static/
    depends_on:
      - site
    networks:
      - simple_net

networks:
  simple_net:
    driver: bridge